name: safe_ship
description: A secure delivery application

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.3.0
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  provider: ^6.0.5
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true